services:
  codegen:
    image: jianshao/code-gen-demo:${image_ver}
    container_name: codegen
    pull_policy: always
    restart: unless-stopped
    environment:
      - https_proxy=${https_proxy:-}
      - no_proxy=${no_proxy:-}
      - PROMPT_TPL_DIR=/home/devel/prompts
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ${PROMPT_TPL_DIR}:/home/devel/prompts
      - ${HOME}/.config:/home/devel/.config
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
